### ISSUE TITLE
Add an alternative way to specify build enviroment variables

### ISSUE THREAD

**Issue by oliverpool** [gokrazy/tools#31]
Currently build variables like GOARM, GOOS and GOARCH are simply forwarded from the current environment with some default values: 
https://github.com/gokrazy/tools/blob/7f0229b37ad1164487e56cb6e73a4d387db96183/cmd/gokr-packer/gotool.go#L15-L28

However this does not play well with `go run`:
```
GOARCH=arm go run github.com/gokrazy/tools/cmd/gokr-packer
    github.com/gokrazy/hello
```

Since `GOARCH` will be used by `go run`, the resulting `gokr-packer` executable will not run on and amd64 machine for instance.

---

I would like to be able to use `go run github.com/gokrazy/tools/cmd/gokr-packer`, so that the `gokr-packer` version can be [managed by `go.mod`](https://github.com/golang/go/issues/25922#issuecomment-402918061) using a `tools.go` file:
```go
//go:build tools

package tools

import (
	_ "github.com/gokrazy/tools/cmd/gokr-packer"
)
```

---

Here are the possible solutions to this problem, that I thought of:
- support prefixed environment variables: `GOKR_GOARCH= go run ...` for instance (which would override `GOARCH)
- add a flag to support build environment file: `go run .../gokr-packer -buildenv=env` with `env` being a file like:
```env
GOARCH=arm
```

What do you think would be the most elegant way to fix this issue ?
I can then try to craft a PR.

**Comment by stapelberg** [comment]
Instead of using `go run`, why not just `go install && gokr-packer`?

If you absolutely want to use `go run`, can you use its `-exec` flag to specify a wrapper that applies environment variables?

I’d like to avoid adding a custom way to pass environment variables.

**Comment by oliverpool** [comment]
> Instead of using `go run`, why not just `go install && gokr-packer`?

Because I wasn't able to find `gokr-packer`afterwards :see_no_evil: it is actually simply in `$(go env GOPATH)/bin/gokr-packer`...
(and it seems faster than `go run`)
