### ISSUE TITLE
Relative replace directives stopped working

### ISSUE THREAD

**Issue by max-te** [gokrazy/tools#49]
I'm using replace directives with relative paths for some instance-specific modules, e.g.
```
replace maxte/gokrazy/gpio-counter => ../../../../gpio-counter
```
Since 626d0c7d065b2849592f70a8858bb88f00627110 this fails when running `gok update` with
```
[...]

Including loadable kernel modules from:
/home/max/go/pkg/mod/github.com/gokrazy/kernel@v0.0.0-20221127041900-e409dc33d0ae/lib/modules
2023/02/25 16:02:09 lstat ../../../../gpio-counter: no such file or directory
```

**Comment by stapelberg** [comment]
Thanks for the report. Can you let me know in which path you’re using the replace directive (absolute path to the go.mod file), and the absolute path of the gpio-counter directory please?

I want to make sure I reproduce the issue the same way.

**Comment by max-te** [comment]
I've tried to reduce this to a simpler case:
I've now just called the module `gpio-counter`. The directory structure is as follows
```
/home/max/vzaehler
- config.json
- builddir
| - gpio-counter
| | - go.mod
| | - go.sum
- gpio-counter
| - go.mod
| - counter.go
```

The `builddir/gpio-counter/go.mod` contains the replace directive
```
replace gpio-counter => ../../gpio-counter
```

When I instead use the absolute path `/home/max/gokrazy/vzaehler/gpio-counter` everything works.

**Comment by stapelberg** [comment]
Thanks for the reproduction steps! I could reproduce the problem.

This should be fixed now with commit https://github.com/gokrazy/tools/commit/7b9dd260c5be1381673582f1faf07805278c56f1

**Comment by max-te** [comment]
I can confirm that this fixed the issue for me. Thank you!
