### ISSUE TITLE
Specifying both -overwrite_boot and -overwrite_root does not result in 2 images

### ISSUE THREAD

**Issue by stapelberg** [gokrazy/tools#5]
Example invocation:

`gokr-packer -overwrite_boot=/tmp/boot.fat -overwrite_root=/tmp/root.fat $GOPROJ`

originally reported in https://github.com/gokrazy/gokrazy/issues/27#issuecomment-298571058

**Comment by gedw99** [comment]
will wait until this is fixed before going forward.
I started to write a golang package to wrap some of the aspects of updating the firmware that handles the differences between Linux and OSX and Windows.

**Comment by stapelberg** [comment]
This shouldn’t block you. As a workaround, you can just call gokr-packer twice in a row:

```
gokr-packer -overwrite_boot=/tmp/boot.fat  $GOPROJ
gokr-packer -overwrite_root=/tmp/root.fat $GOPROJ
```

**Comment by gedw99** [comment]
thanks :)
