### ISSUE TITLE
SBOM inconsistency gok sbom vs gok overwrite/update

### ISSUE THREAD

**Issue by damdo** [gokrazy/tools#64]
Turns out that https://github.com/gokrazy/tools/pull/61 only fixed the SBOM inconsistencies that were caused by config.Struct pointers and by the Sudo flag, that was set [here](https://github.com/gokrazy/tools/pull/61/files#diff-e92c79e77d56e8f8dca8f4a40e1a942331870e428ee4db4a2f4c5b1b3ef29843L1008-L1011).
They did not fix the diff that is generated from the other fields in the `config.InternalCompatibilityFlags`, which I didn't realise, are set depending on the update mode.

- If `gok sbom` is used, no `config.InternalCompatibilityFlags` are set.
- If `gok overwrite --full` is used `config.InternalCompatibilityFlags.Overwrite` and `config.InternalCompatibilityFlags.TargetStorageBytes` are set
- If `gok overwrite --gaf` is used, nothing is set
- If `gok update` is used, `config.InternalCompatibilityFlags.Udpdate` (optionally Insecure, Testboot) is set.

These end up being accounted for when the `config.Struct` is stringyfied and formatted in hex, influencing the hash value for the config.json, ending up influencing the one of the final SBOM hash.

This is an issue when `gok sbom` is used to check for changes between the running instance (SBOM) and the current local instance folder, as it results in different SBOM hashes, which in these cases might mean an infinite loop of unnecessary updates.

Do you have any idea on how we could circumvent this issue?

I know @stapelberg [mentioned](https://github.com/gokrazy/tools/pull/61#issuecomment-1722529971) that ignoring the `config.InternalCompatibilityFlags` that would mean same SBOMs for an instance with differing `InternalCompatibilityFlags`, but I would prefer this poison versus having unusable SBOMs and unnecessary updates (unless we can come up with a better solution for this :)).

WDYT?

**Comment by stapelberg** [comment]
I wonder if it could be a viable strategy to calculate the SBOM **before** setting InternalCompatibilityFlags? That way, user-specified InternalCompatibilityFlags would still be reflected in the SBOM, but tool-specified InternalCompatibilityFlags would not.

**Comment by stapelberg** [comment]
Shower thoughts: an alternative to the approach of generate-sbom-before is to split up the user-provided vs. tool-specified InternalCompatibilityFlags into two separate fields and use accessors.

Or, the galaxy brain solution could be to get rid of all InternalCompatibilityFlags (one by one) and solve the problem that way.

**Comment by damdo** [comment]
Attempted approach 1 here: https://github.com/gokrazy/tools/pull/66
